services:
  - type: web
    name: crypto-beach-soccer-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: ORIGIN
        value: https://crypto-beach-soccer.netlify.app
    autoDeploy: true